import { SIGNUP_FORM_FIELD_KEY } from './frame/signup-form/signup-form.type'

export const SIGNUP_FIELD_NAME = {
    LOGIN: 'login',
    PASSWORD: 'password'
}

export const SIGNUP_FORM_FIELD_NAME = {
    [SIGNUP_FORM_FIELD_KEY.LOGIN]: SIGNUP_FIELD_NAME.LOGIN,
    [SIGNUP_FORM_FIELD_KEY.PASSWORD]: SIGNUP_FIELD_NAME.PASSWORD,
}

export const SIGNUP_ACTION_TYPE = {
    SIGNUP_FORM_PENDING: "SIGNUP_ACTION_TYPE.SIGNUP_FORM_PENDING",
    SIGNUP_FORM_SUCCESS: "SIGNUP_ACTION_TYPE.SIGNUP_FORM_SUCCESS",
    SIGNUP_FORM_ERROR: "SIGNUP_ACTION_TYPE.SIGNUP_FORM_ERROR",
    SIGNUP_FORM_RESET: "SIGNUP_ACTION_TYPE.SIGNUP_FORM_RESET",
}